add priorities to task
AY2223S2-CS2103T-T17-4/tp pull request #72
Opened 2023-03-24 06:20 UTC by bryanongjx

Now you can add priorities to tasks with format specified "/p"

Note priorities are only accepted in the form "low" / "medium" / "high"

An example command: task add d/feed fish p/medium

Also note priorities are optional. if not specified, it will be null.
For example, the command: task add d/feed fish will have a null priority

2023-03-24 06:22 UTC, bryanongjx commented
Also note that you have to reset the tasklist.json file under data as the current tasklist with no priority attribute will crash the code. once resetted, it should work fine

2023-03-24 06:38 UTC, bryanongjx commented
im not sure where the trailing whitespace is coming from. i checked the commit and there is no whitespace. the checkstyle error came after i solved a merge conflict with the reminders branch

2023-03-24 07:08 UTC, bokuanT requested changes

2023-03-24 07:08 UTC, bokuanT commented on src/main/java/seedu/address/model/task/Task.java
> +
I checked this part, there seems to be ' ' whitespace on the line after the hasPriority() method i.e if you click the right arrow key it doesn't immediately go to the next line but continues on the same line on the ' ' chars. Delete these ' ' chars and it should be fine

2023-03-28 04:18 UTC, ryanchua00 requested changes
Fix build failure in TaskFeedingReminder

2023-03-30 08:29 UTC, closed without merging